Adds summary
Miksel90/development-platforms pull request #37
Opened 2024-02-08 09:20 UTC by Spookyrumble

2024-02-08 19:48 UTC, Miksel90 commented on src/content/docs/frameworks/Flutter/Flutter-case-study.md
>  ![c823e53b3a1a7b0d36a9](https://github.com/Miksel90/development-platforms/assets/113434165/a4622638-22ee-4e8e-a7c8-ae86b5a8f8c0)
Cool! =D

2024-02-08 19:54 UTC, Miksel90 commented on src/content/docs/frameworks/Flutter/Flutter-case-study.md
> +Flutter can be used more things. Like creating this little game.
```suggestion
Flutter can be used for different things, like creating this game.
```

2024-02-08 19:54 UTC, Miksel90 commented on src/content/docs/frameworks/Flutter/Flutter-case-study.md
> +The study goes into the architecture of Flutter, emphasizing its widget-based design where everything, from buttons to layout, is a widget.
I think we need to either elaborate on this just a little or just cut the sentence.

2024-02-08 19:55 UTC, Miksel90 requested changes
LGTM

nNice logo =)

2024-02-08 19:55 UTC, Miksel90 commented on src/content/docs/frameworks/Flutter/Flutter-case-study.md
> +The study goes into the architecture of Flutter, emphasizing its widget-based design where everything, from buttons to layout, is a widget.
This was supposed to be the widget sentence.

2024-02-08 20:42 UTC, Spookyrumble commented on src/content/docs/frameworks/Flutter/Flutter-case-study.md
> +The study goes into the architecture of Flutter, emphasizing its widget-based design where everything, from buttons to layout, is a widget.
remove it

2024-02-09 08:47 UTC, Miksel90 commented on src/content/docs/frameworks/Flutter/Flutter-case-study.md
> +The study goes into the architecture of Flutter, emphasizing its widget-based design where everything, from buttons to layout, is a widget.
```suggestion

```

2024-02-09 09:35 UTC, Miksel90 approved these changes

2024-02-09 09:35 UTC, merged